// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Code    int64      `json:"code"`
	Message string     `json:"message"`
	Data    *LoginData `json:"data"`
}

type LoginData struct {
	Jwt  string `json:"jwt"`
	Role *Role  `json:"role"`
}

type Role struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}
