// Code generated by goctl. DO NOT EDIT.
// Source: user_score.proto

package userscore

import (
	"context"
	score2 "rpc-common/user-score/types/score"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserScoreRequest  = score2.UserScoreRequest
	UserScoreResponse = score2.UserScoreResponse

	UserScore interface {
		SaveUserScore(ctx context.Context, in *UserScoreRequest, opts ...grpc.CallOption) (*UserScoreResponse, error)
		// saveUserScoreCallback 分布式事务中提交失败之后 回滚时需要执行一个callback
		SaveUserScoreCallback(ctx context.Context, in *UserScoreRequest, opts ...grpc.CallOption) (*UserScoreResponse, error)
	}

	defaultUserScore struct {
		cli zrpc.Client
	}
)

func NewUserScore(cli zrpc.Client) UserScore {
	return &defaultUserScore{
		cli: cli,
	}
}

func (m *defaultUserScore) SaveUserScore(ctx context.Context, in *UserScoreRequest, opts ...grpc.CallOption) (*UserScoreResponse, error) {
	client := score2.NewUserScoreClient(m.cli.Conn())
	return client.SaveUserScore(ctx, in, opts...)
}

// saveUserScoreCallback 分布式事务中提交失败之后 回滚时需要执行一个callback
func (m *defaultUserScore) SaveUserScoreCallback(ctx context.Context, in *UserScoreRequest, opts ...grpc.CallOption) (*UserScoreResponse, error) {
	client := score2.NewUserScoreClient(m.cli.Conn())
	return client.SaveUserScoreCallback(ctx, in, opts...)
}
